### ISSUE TITLE
NameError: name 'false' is not defined

### ISSUE THREAD

**Issue by maitray16** [blackducksoftware/hub-rest-api-python#164]
Hi, I am trying to play around with the examples and getting an error when trying to use print_vulnerability.py.  My guess is the error is coming from https://github.com/blackducksoftware/hub-rest-api-python/blob/c9bd042462881126de7e53dcf63c289c7443f6d8/blackduck/Vulnerabilities.py#L16 
The error is 
```
"classifications": [
NameError: name 'false' is not defined
```
Let me know if this can be fixed or what should I change from my side.

**Comment by skiyooka** [comment]
I took quick look at that endpoint and it is working as expected with both HubInstance and Client. In essence the endpoint fetches a specific vulnerability by id and will return a status_code of 200 if found or 404 if not.
GET "/api/vulnerabilities/CVE-2016-4009"

The NameError: name 'false' is not defined makes me suspect that you are using 'false' instead of 'False' (note capitalization) in your Python code.
