### ISSUE TITLE
Allow time parameter for deleting empty projects and projects

### ISSUE THREAD

**Issue by ramaprakashganesan** [blackducksoftware/hub-rest-api-python#173]
https://github.com/blackducksoftware/hub-rest-api-python/blob/master/examples/delete_empty_projects_and_versions.py just seems to directly delete all empty projects and all empty versions in any projects. 
Request to add parameter for its execution to provide number of days since that particular project or version was created.
Eg: Delete all projects and all versions in all projects that are empty, and created 30 days before or earlier. 

https://github.com/blackducksoftware/hub-rest-api-python/blob/master/examples/delete_empty_projects.py does allow a time parameter. If similar logic to provide time were provided for versions also, it would be helpful. 
It is better if the time parameter is in the form of number of days since creation, rather than in date format (YYYY-MM-DD). 

Please see if possible to implement this. Would be helpful for multiple customers.

**Comment by gsnyder2007** [comment]
Thanks for the feedback. The examples are just that and are provided as-is. You're welcome to fork and change however you want OR make a PR to incorporate some additional capability like this. I'm sure it would be quite possible to implement what you've asked for and one of the maintainers/contributors may be able to get to it sooner rather than later, but if you don't want to wait we welcome PR's so feel free to suggest something.
