### ISSUE TITLE
Why using list comprehensions to fetch from generators?

### ISSUE THREAD

**Issue by thaljef** [blackducksoftware/hub-rest-api-python#200]
At lines [123](https://github.com/blackducksoftware/hub-rest-api-python/blob/107b75f7159d0e1d7b9201ec54dc625f41ebaa9b/examples/bd-upstream-copyrights/get_upstream_copyrights.py#L123) and [133](https://github.com/blackducksoftware/hub-rest-api-python/blob/107b75f7159d0e1d7b9201ec54dc625f41ebaa9b/examples/bd-upstream-copyrights/get_upstream_copyrights.py#L133) in `get_upstream_copyrights.txt` a list comprehension is used to fetch all values from the generator returned by `get_resource`. Why is this?  Wouldn't `list()` accomplish the exact same thing and be easier to read?

**Comment by gsnyder2007** [comment]
The generator in get_resource handles paging of results from the REST API so that the caller does not have to include the scaffolding code to manage paging. This makes the client code much simpler than it was with the old bindings using HubInstance.

So, if the calling code needs ALL the results it needs to iterate over the generator until all the results have been accumulated. One way to do this is with a comprehension, and its arguably the best way. If you find a better method please submit a PR.

**Comment by thaljef** [comment]
Yes, I understand the virtue of the generator. My question is whether there is some hidden benefit to using a list comprehension instead of `list()` when you want to pull all the values from the generator.

**Comment by AR-Calder** [comment]
@thaljef looking at the underlying implementation, technically casting to list directly will be faster as it more directly translates to C. This difference might standout on  endpoints that return many pages of results i.e. component-vulnerabilities but it is unlikely to make any noticeable difference on version endpoints. 

That being said, if you feel strongly enough about this perhaps you could create a PR for it?
