### ISSUE TITLE
Creating Notices File in HTML format fails with HTTP 412

### ISSUE THREAD

**Issue by ianhende** [blackducksoftware/hub-rest-api-python#79]
In HubRestApi.py, the formats for the Notices File report are restricted to TEXT and HTML:
```
    valid_notices_formats = ["TEXT", "HTML"]
    def create_version_notices_report(self, version, format="TEXT"):
        assert format in HubInstance.valid_notices_formats, "Format must be one of {}".format(HubInstance.valid_notices_formats)
```
When my application code specifies "HTML", however, I get a HTTP 412 response status.

If I modify the code above to accept JSON instead of HTML, it works and I'm able to download a zip file containing the Notices File in JSON format. (TEXT format also works.)

**Comment by gsnyder2007** [comment]
Investigating

**Comment by ianhende** [comment]
Hi Glenn - Thanks for invesitgating.

FYI what I actually want is the JSON response, which my application (a microservice) can easily parse to populate a Word docx template (which has branding/metadata/copyright etc. specific to my employer).

**Comment by gsnyder2007** [comment]
@ianhende thanks, that's good to know. I'm taking a bit longer to finish this as a noticed some other things in there that should be refactored. Since I originally wrote the code to generate the reports some things have changed and I've realized I made some mistakes in the initial implementation beyond what you've pointed out here. My goal is to finish and push something tomorrow so by next week hoping to have something for you to try/verify it works for your use case. Thanks for your patience.

**Comment by gsnyder2007** [comment]
See https://github.com/blackducksoftware/hub-rest-api-python/pull/80 . I've ask for a review and assuming that happens tomorrow I will push this version up to PyPi

**Comment by gsnyder2007** [comment]
I've updated and pushed v0.0.42 which provides a solution to this issue. See [generate_notices_report_for_project_version.py](https://github.com/blackducksoftware/hub-rest-api-python/blob/master/examples/generate_notices_report_for_project_version.py) and the option for generating notices content in JSON.

**Comment by ianhende** [comment]
Many thanks @gsnyder2007 - I've upgraded to 0.0.43 and confirm I get the notices file in JSON format ok.
